version: '3.7'
services:
  webdb:
    image: postgres:latest
    container_name: webdb
    volumes:
      - ./data/db/postgresql:/var/lib/postgresql/data
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataforum
    # networks:
    #   - webdb_nw
  webapp:
    build: ./
    container_name: webapp
    image: datascience/webapp:1.0.0
    links:
      - webdb
    # ports:
    #   - 5000:5000
    #   - 5050:5050
    # expose:
    #   - 5000
    volumes:
      - ./backend:/data/webapp
      - ./backend/uwsgi.ini:/etc/uwsgi/uwsgi.ini
    # networks:
    #   - webdb_nw
    #   - webapp_nw
  nginx:
    image: nginx:latest
    container_name: nginx
    links:
      - webapp
    depends_on:
      - webapp
    volumes:
      - ./data/nginx/log:/var/log/nginx
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      - 443:443
    restart: always
    # networks:
    #   - webapp_nw

  # networks:
  #   webdb_nw:
  #     driver: bridge
  #   webapp_nw:
  #     driver: bridge

  volumes:
    pgdata:
      external: true
