version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: datascience_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd"
      MYSQL_DATABASE: "datascience"
      MYSQL_USER: "datascience"
      MYSQL_PASSWORD: "Passw0rd"
    volumes:
      - ./data/db/mysql:/var/lib/mysql
    ports:
      - 53306:3306
    networks:
      - dbnetwork

#docker network create --subnet=172.30.0.0/24 dbnetwork
networks:
  dbnetwork:
    external: true
