version: '2.2'
services:
  webdb:
    image: postgres:latest
    volumes:
      - "./data/webdb/postgres/data:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataforum
    # networks:
    #   - webdb_nw
  webapp:
    build: ./webapp
    container_name: webapp
    links:
      - webdb
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - ../backend:/data/webapp
      - ../webapp/uwsgi.ini:/etc/uwsgi/uwsgi.ini
    # networks:
    #   - webdb_nw
    #   - webapp_nw
  nginx:
    image: nginx:latest
    links:
      - webapp
    depends_on:
      - webapp
    volumes:
      - "./data/nginx/log:/var/log/nginx"
      - "./nginx/conf.d/:/etc/nginx/conf.d/"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    # networks:
    #   - webapp_nw

  # networks:
  #   webdb_nw:
  #     driver: bridge
  #   webapp_nw:
  #     driver: bridge