"""empty message

Revision ID: 521890a74b83
Revises: f9b2b6a25094
Create Date: 2020-03-17 17:31:36.547260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521890a74b83'
down_revision = 'f9b2b6a25094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'info')
    # ### end Alembic commands ###
